### PR TITLE
Unicode support 🐕 +more

### PR DESCRIPTION
**Pull request by ghost**
- Text uses internally only wchar_t
- Without an code change 8 Bit text are supported
- With code change 16 Bit text are supported
- No AHK implementation of the Unicode functions because I don't know how to do this
- The memory usage is maybe lower (loading just the characters that needed and then sharing it)
- Performance might be worse than before

Fixing #30 #32 and maybe #6

Code review and testing would be nice because I maybe missed something

### CODE REVIEW

**Comment by agrippa1994** [comment]
I like the shared font implementation. Did you implement this on your own?

**Comment by shadowlif** [comment]
Yes

**Comment by shadowlif** [comment]
- Fixed #19

**Review by agrippa1994 — APPROVED** [review]
Approved. Can i merge it?

**Comment by shadowlif** [comment]
I think so. Everything should be right.

**Pull request merged**
